#!/usr/bin/env node
// Scan the repo for per-package agent instruction files and emit a root-level
// getting-started index (.agent.md + .agent.json) that an LLM can read first.
//
// Inputs  : <ROOT>/<pkg>/.agent*/ *.md  and any <ROOT>/<pkg>/.agent.md
// Outputs : <ROOT>/.agent.md   (human + LLM readable)
//           <ROOT>/.agent.json (machine readable)
//
// Usage:
//   node .agent/scan.mjs            # write both outputs
//   node .agent/scan.mjs --check    # fail if outputs are stale (CI-friendly)
//   node .agent/scan.mjs --stdout   # print .agent.md to stdout, write nothing

import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const AGENT_DIR_NAMES = new Set([".agent", ".agents"]);
const FLAT_FILE_NAMES = new Set([".agent.md", ".agents.md"]);
const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  ".venv",
  "dist",
  "build",
  "__pycache__",
  ".cache",
  ".next",
  ".nuxt",
  ".smoke-logs",
  "coverage",
  ".agent", // the tool itself
]);

const args = new Set(process.argv.slice(2));
const CHECK = args.has("--check");
const STDOUT = args.has("--stdout");

// --- minimal YAML frontmatter parser (handles the shape these files use) ----

function parseFrontmatter(src) {
  if (!src.startsWith("---")) return { data: {}, body: src };
  const end = src.indexOf("\n---", 3);
  if (end === -1) return { data: {}, body: src };
  const raw = src.slice(3, end).replace(/^\r?\n/, "");
  const body = src.slice(end + 4).replace(/^\r?\n/, "");
  const data = {};
  const lines = raw.split(/\r?\n/);
  let currentListKey = null;
  for (const line of lines) {
    if (!line.trim()) continue;
    const listItem = line.match(/^\s+-\s+(.*)$/);
    if (listItem && currentListKey) {
      data[currentListKey].push(unquote(listItem[1].trim()));
      continue;
    }
    const kv = line.match(/^([A-Za-z0-9_-]+)\s*:\s*(.*)$/);
    if (!kv) {
      currentListKey = null;
      continue;
    }
    const [, key, rest] = kv;
    if (rest === "" || rest === undefined) {
      data[key] = [];
      currentListKey = key;
    } else {
      data[key] = unquote(rest.trim());
      currentListKey = null;
    }
  }
  return { data, body };
}

function unquote(s) {
  if (
    (s.startsWith('"') && s.endsWith('"')) ||
    (s.startsWith("'") && s.endsWith("'"))
  ) {
    return s.slice(1, -1);
  }
  return s;
}

// --- discovery --------------------------------------------------------------

async function listSubdirs(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  return entries
    .filter((e) => e.isDirectory() && !e.name.startsWith(".") && !SKIP_DIRS.has(e.name))
    .map((e) => e.name)
    .sort();
}

async function findAgentSources(pkgDir) {
  // Returns a list of absolute .md paths that describe agent instructions for this package.
  const found = [];
  let direct;
  try {
    direct = await readdir(pkgDir, { withFileTypes: true });
  } catch {
    return found;
  }
  for (const e of direct) {
    if (e.isDirectory() && AGENT_DIR_NAMES.has(e.name)) {
      const sub = join(pkgDir, e.name);
      let files;
      try {
        files = await readdir(sub, { withFileTypes: true });
      } catch {
        continue;
      }
      for (const f of files) {
        if (f.isFile() && f.name.endsWith(".md")) found.push(join(sub, f.name));
      }
    } else if (e.isFile() && FLAT_FILE_NAMES.has(e.name)) {
      found.push(join(pkgDir, e.name));
    }
  }
  found.sort();
  return found;
}

async function parseAgentFile(absPath) {
  const raw = await readFile(absPath, "utf8");
  const { data, body } = parseFrontmatter(raw);
  const rel = relative(ROOT, absPath);
  return {
    file: rel,
    name: data.name ?? basenameNoExt(absPath),
    scope: data.scope ?? null,
    description: data.description ?? firstHeading(body) ?? "",
    triggers: Array.isArray(data.triggers) ? data.triggers : [],
  };
}

function basenameNoExt(p) {
  return p.split("/").pop().replace(/\.md$/, "");
}

function firstHeading(body) {
  const m = body.match(/^#\s+(.+)$/m);
  return m ? m[1].trim() : null;
}

// --- rendering --------------------------------------------------------------

function renderMarkdown(model) {
  const lines = [];
  lines.push("<!-- GENERATED by .agent/scan.mjs — do not edit by hand. -->");
  lines.push(`<!-- Regenerate with: node .agent/scan.mjs -->`);
  lines.push("");
  lines.push(`# ${model.repo} — Agent Start Here`);
  lines.push("");
  lines.push(
    "This file is the LLM entry point for this repo. It indexes the per-package agent instruction files so an assistant can pick the right skill before touching code."
  );
  lines.push("");
  lines.push(`- **Repo root:** \`${model.repo}\``);
  lines.push(`- **Generated:** ${model.generatedAt}`);
  lines.push(`- **Skills indexed:** ${model.totalSkills} across ${model.packages.length} package(s)`);
  lines.push("");

  lines.push("## How to use");
  lines.push("");
  lines.push("1. Read the repo `README.md` for layout and package roles.");
  lines.push("2. Pick the package you're touching (table below).");
  lines.push("3. Open the matching skill file under that package's `.agents/` directory — frontmatter `triggers` tell you when each skill applies.");
  lines.push("4. Regenerate this file with `node .agent/scan.mjs` after adding/removing skills.");
  lines.push("");

  if (model.packages.length > 0) {
    lines.push("## Packages");
    lines.push("");
    lines.push("| Package | Skills | Source |");
    lines.push("| --- | ---: | --- |");
    for (const pkg of model.packages) {
      lines.push(`| \`${pkg.name}/\` | ${pkg.skills.length} | \`${pkg.sourceDir}\` |`);
    }
    lines.push("");
  }

  for (const pkg of model.packages) {
    lines.push(`## ${pkg.name}`);
    lines.push("");
    lines.push(`Source: \`${pkg.sourceDir}\``);
    lines.push("");
    for (const skill of pkg.skills) {
      lines.push(`### \`${skill.name}\``);
      lines.push("");
      if (skill.description) {
        lines.push(skill.description);
        lines.push("");
      }
      lines.push(`- **File:** \`${skill.file}\``);
      if (skill.scope) lines.push(`- **Scope:** \`${skill.scope}\``);
      if (skill.triggers.length > 0) {
        lines.push(`- **Triggers:** ${skill.triggers.map((t) => `\`${t}\``).join(", ")}`);
      }
      lines.push("");
    }
  }

  if (model.orphans.length > 0) {
    lines.push("## Other agent files");
    lines.push("");
    for (const o of model.orphans) {
      lines.push(`- \`${o.file}\` — ${o.description || o.name}`);
    }
    lines.push("");
  }

  lines.push("## Regeneration");
  lines.push("");
  lines.push("```bash");
  lines.push("node .agent/scan.mjs          # rewrite .agent.md and .agent.json");
  lines.push("node .agent/scan.mjs --check  # CI: fail if outputs are stale");
  lines.push("```");
  lines.push("");
  return lines.join("\n");
}

function renderJson(model) {
  return JSON.stringify(model, null, 2) + "\n";
}

// --- main -------------------------------------------------------------------

async function main() {
  const repoName = (await safeReadJson(join(ROOT, "package.json")))?.name
    ?? ROOT.split("/").pop();

  const subdirs = await listSubdirs(ROOT);
  const packages = [];
  const orphans = [];

  for (const name of subdirs) {
    const pkgDir = join(ROOT, name);
    const files = await findAgentSources(pkgDir);
    if (files.length === 0) continue;
    const skills = [];
    for (const f of files) skills.push(await parseAgentFile(f));
    skills.sort((a, b) => a.name.localeCompare(b.name));
    const sourceDir = relative(ROOT, dirname(files[0])) || ".";
    packages.push({ name, sourceDir, skills });
  }

  // Root-level .agent.md / .agent/ stray files (besides outputs)
  const rootEntries = await readdir(ROOT, { withFileTypes: true });
  for (const e of rootEntries) {
    if (e.isFile() && FLAT_FILE_NAMES.has(e.name) && e.name !== ".agent.md") {
      orphans.push(await parseAgentFile(join(ROOT, e.name)));
    }
  }

  const totalSkills = packages.reduce((n, p) => n + p.skills.length, 0);
  const model = {
    repo: repoName,
    root: ".",
    generatedAt: new Date().toISOString(),
    generator: ".agent/scan.mjs",
    totalSkills,
    packages,
    orphans,
  };

  const md = renderMarkdown(model);
  const json = renderJson(model);

  if (STDOUT) {
    process.stdout.write(md);
    return;
  }

  const mdPath = join(ROOT, ".agent.md");
  const jsonPath = join(ROOT, ".agent.json");

  if (CHECK) {
    const mdCurrent = existsSync(mdPath) ? await readFile(mdPath, "utf8") : "";
    const jsonCurrent = existsSync(jsonPath) ? await readFile(jsonPath, "utf8") : "";
    // ignore generatedAt drift in check mode
    const strip = (s) => s.replace(/"generatedAt":\s*"[^"]*"/, '"generatedAt":"<stripped>"')
                          .replace(/- \*\*Generated:\*\* [^\n]*/, "- **Generated:** <stripped>");
    if (strip(md) !== strip(mdCurrent) || strip(json) !== strip(jsonCurrent)) {
      process.stderr.write(
        "[.agent/scan.mjs] outputs are stale — run `node .agent/scan.mjs`.\n"
      );
      process.exit(1);
    }
    process.stdout.write(`[.agent/scan.mjs] ok — ${totalSkills} skills across ${packages.length} package(s).\n`);
    return;
  }

  await writeFile(mdPath, md);
  await writeFile(jsonPath, json);
  process.stdout.write(
    `[.agent/scan.mjs] wrote .agent.md + .agent.json — ${totalSkills} skills across ${packages.length} package(s).\n`
  );
}

async function safeReadJson(p) {
  try {
    await stat(p);
    return JSON.parse(await readFile(p, "utf8"));
  } catch {
    return null;
  }
}

main().catch((err) => {
  process.stderr.write(`[.agent/scan.mjs] ${err?.stack || err}\n`);
  process.exit(1);
});
